apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: autoparts
type: Opaque
stringData:
  POSTGRES_USER: autoparts_user
  POSTGRES_PASSWORD: autoparts_password
  POSTGRES_DB: autoparts_db