"""add versioning to inventory balance

Revision ID: 1a105655c32b
Revises: 8d15d6f48730
Create Date: 2026-04-25 18:18:03.117177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a105655c32b'
down_revision: Union[str, Sequence[str], None] = '8d15d6f48730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('inventory_balance', sa.Column('version_num', sa.Integer(), nullable=True), schema='autoparts_owner')

    op.execute("""
        update autoparts_owner.inventory_balance
        set version_num = 1
        where version_num is null
    """)

    op.alter_column('inventory_balance', 'version_num', existing_type=sa.Integer(), nullable=False, schema='autoparts_owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_balance', 'version_num', schema='autoparts_owner')
    # ### end Alembic commands ###
