"""create shipment table

Revision ID: 21066c83b6b2
Revises: 2990cfb7649b
Create Date: 2026-04-26 17:18:56.817793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21066c83b6b2'
down_revision: Union[str, Sequence[str], None] = '2990cfb7649b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment',
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('shipment_number', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('shipment_status', sa.String(length=30), nullable=False),
    sa.Column('carrier_name', sa.String(length=100), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('shipped_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("shipment_status in ('CREATED', 'SHIPPED', 'DELIVERED', 'RETURNED')", name='ck_shipment_status_allowed'),
    sa.ForeignKeyConstraint(['order_id'], ['autoparts_owner.sales_order.order_id'], ),
    sa.PrimaryKeyConstraint('shipment_id'),
    sa.UniqueConstraint('shipment_number'),
    schema='autoparts_owner'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment', schema='autoparts_owner')
    # ### end Alembic commands ###
