"""create product category and brand tables

Revision ID: 25a6e4ca44d5
Revises: bcba62e9573b
Create Date: 2026-04-24 18:01:31.540290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25a6e4ca44d5'
down_revision: Union[str, Sequence[str], None] = 'bcba62e9573b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_brand',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('brand_id'),
    sa.UniqueConstraint('brand_name'),
    schema='autoparts_owner'
    )
    op.create_table('product_category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_category_id'], ['autoparts_owner.product_category.category_id'], ),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name'),
    schema='autoparts_owner'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_category', schema='autoparts_owner')
    op.drop_table('product_brand', schema='autoparts_owner')
    # ### end Alembic commands ###
