"""add snapshots and index to inventory movement

Revision ID: 308429d23eb7
Revises: 3a2c811bbf86
Create Date: 2026-04-25 17:12:32.303004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '308429d23eb7'
down_revision: Union[str, Sequence[str], None] = '3a2c811bbf86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('inventory_movement', sa.Column('resulting_on_hand_qty', sa.Integer(), nullable=True), schema='autoparts_owner')
    op.add_column('inventory_movement', sa.Column('resulting_reserved_qty', sa.Integer(), nullable=True), schema='autoparts_owner')

    op.execute("""
        update autoparts_owner.inventory_movement
        set resulting_on_hand_qty = 0,
            resulting_reserved_qty = 0
        where resulting_on_hand_qty is null
           or resulting_reserved_qty is null
    """)

    op.alter_column('inventory_movement', 'resulting_on_hand_qty', existing_type=sa.Integer(), nullable=False, schema='autoparts_owner')
    op.alter_column('inventory_movement', 'resulting_reserved_qty', existing_type=sa.Integer(), nullable=False, schema='autoparts_owner')

    op.create_index('ix_inventory_movement_warehouse_product', 'inventory_movement', ['warehouse_id', 'product_id'], unique=False, schema='autoparts_owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_movement_warehouse_product', table_name='inventory_movement', schema='autoparts_owner')
    op.drop_column('inventory_movement', 'resulting_reserved_qty', schema='autoparts_owner')
    op.drop_column('inventory_movement', 'resulting_on_hand_qty', schema='autoparts_owner')
    # ### end Alembic commands ###
