"""create inventory movement table

Revision ID: 3a2c811bbf86
Revises: 73dba836582b
Create Date: 2026-04-25 16:33:24.968350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a2c811bbf86'
down_revision: Union[str, Sequence[str], None] = '73dba836582b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_movement',
    sa.Column('inventory_movement_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('comment_text', sa.String(length=500), nullable=True),
    sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['autoparts_owner.product.product_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['autoparts_owner.warehouse.warehouse_id'], ),
    sa.PrimaryKeyConstraint('inventory_movement_id'),
    schema='autoparts_owner'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_movement', schema='autoparts_owner')
    # ### end Alembic commands ###
