"""create warehouse table

Revision ID: 4d97dab931cf
Revises: 0fff851f62fd
Create Date: 2026-04-24 17:36:28.791230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d97dab931cf'
down_revision: Union[str, Sequence[str], None] = '0fff851f62fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse',
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_code', sa.String(length=30), nullable=False),
    sa.Column('warehouse_name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('warehouse_id'),
    sa.UniqueConstraint('warehouse_code'),
    schema='autoparts_owner'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouse', schema='autoparts_owner')
    # ### end Alembic commands ###
