"""create inventory balance table

Revision ID: 73dba836582b
Revises: ee3e8eac88a8
Create Date: 2026-04-24 19:08:33.233489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73dba836582b'
down_revision: Union[str, Sequence[str], None] = 'ee3e8eac88a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_balance',
    sa.Column('inventory_balance_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('on_hand_qty', sa.Integer(), nullable=False),
    sa.Column('reserved_qty', sa.Integer(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['autoparts_owner.product.product_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['autoparts_owner.warehouse.warehouse_id'], ),
    sa.PrimaryKeyConstraint('inventory_balance_id'),
    sa.UniqueConstraint('warehouse_id', 'product_id', name='uq_inventory_balance_warehouse_product'),
    schema='autoparts_owner'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_balance', schema='autoparts_owner')
    # ### end Alembic commands ###
