"""create payment table

Revision ID: ae35bc1b0369
Revises: dd184798b75f
Create Date: 2026-04-26 18:33:40.391169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae35bc1b0369'
down_revision: Union[str, Sequence[str], None] = 'dd184798b75f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('payment_number', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("payment_method in ('CARD', 'PAYPAL', 'BANK_TRANSFER')", name='ck_payment_method_allowed'),
    sa.CheckConstraint("payment_status in ('PENDING', 'PAID', 'FAILED', 'REFUNDED')", name='ck_payment_status_allowed'),
    sa.CheckConstraint('amount >= 0', name='ck_payment_amount_nonnegative'),
    sa.ForeignKeyConstraint(['order_id'], ['autoparts_owner.sales_order.order_id'], ),
    sa.PrimaryKeyConstraint('payment_id'),
    sa.UniqueConstraint('payment_number'),
    schema='autoparts_owner'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment', schema='autoparts_owner')
    # ### end Alembic commands ###
