"""add timestamps to product and warehouse

Revision ID: bcba62e9573b
Revises: 4d97dab931cf
Create Date: 2026-04-24 17:57:43.138125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcba62e9573b'
down_revision: Union[str, Sequence[str], None] = '4d97dab931cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=False), schema='autoparts_owner')
    op.add_column('product', sa.Column('updated_datetime', sa.DateTime(timezone=True), nullable=False), schema='autoparts_owner')
    op.add_column('warehouse', sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=False), schema='autoparts_owner')
    op.add_column('warehouse', sa.Column('updated_datetime', sa.DateTime(timezone=True), nullable=False), schema='autoparts_owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouse', 'updated_datetime', schema='autoparts_owner')
    op.drop_column('warehouse', 'created_datetime', schema='autoparts_owner')
    op.drop_column('product', 'updated_datetime', schema='autoparts_owner')
    op.drop_column('product', 'created_datetime', schema='autoparts_owner')
    # ### end Alembic commands ###
