"""create sales order tables

Revision ID: ec7a3715a5b6
Revises: 1a105655c32b
Create Date: 2026-04-26 12:41:09.950546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec7a3715a5b6'
down_revision: Union[str, Sequence[str], None] = '1a105655c32b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('order_status', sa.String(length=30), nullable=False),
    sa.Column('order_total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('order_number'),
    schema='autoparts_owner'
    )
    op.create_table('sales_order_item',
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('line_amount >= 0', name='ck_sales_order_item_line_amount_nonnegative'),
    sa.CheckConstraint('qty > 0', name='ck_sales_order_item_qty_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_sales_order_item_unit_price_nonnegative'),
    sa.ForeignKeyConstraint(['order_id'], ['autoparts_owner.sales_order.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['autoparts_owner.product.product_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['autoparts_owner.warehouse.warehouse_id'], ),
    sa.PrimaryKeyConstraint('order_item_id'),
    schema='autoparts_owner'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_order_item', schema='autoparts_owner')
    op.drop_table('sales_order', schema='autoparts_owner')
    # ### end Alembic commands ###
