"""add category and brand to product

Revision ID: ee3e8eac88a8
Revises: 25a6e4ca44d5
Create Date: 2026-04-24 18:04:50.318165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee3e8eac88a8'
down_revision: Union[str, Sequence[str], None] = '25a6e4ca44d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category_id', sa.Integer(), nullable=True), schema='autoparts_owner')
    op.add_column('product', sa.Column('brand_id', sa.Integer(), nullable=True), schema='autoparts_owner')
    op.create_foreign_key(None, 'product', 'product_category', ['category_id'], ['category_id'], source_schema='autoparts_owner', referent_schema='autoparts_owner')
    op.create_foreign_key(None, 'product', 'product_brand', ['brand_id'], ['brand_id'], source_schema='autoparts_owner', referent_schema='autoparts_owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', schema='autoparts_owner', type_='foreignkey')
    op.drop_constraint(None, 'product', schema='autoparts_owner', type_='foreignkey')
    op.drop_column('product', 'brand_id', schema='autoparts_owner')
    op.drop_column('product', 'category_id', schema='autoparts_owner')
    # ### end Alembic commands ###
